#定义服务端口
server:
  port: 8001
#实体类的别名,mybatis的核心配置文件，xml配置文件
mybatis:
  type-aliases-package: com.gh.pojo #实体类的别名
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/material/*.xml
#spring的相关配置,名称，数据源，驱动
spring:
  application:
    name: GONGHUI-SERVICE-MATERIALS
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/materials?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root


